"""Memory Arbiter — handles conflicting facts via temporal supersede.

Design principle (from plan): conflicts never delete.  Instead:
  1. The old fact receives `expired_at = now()` + `supersedes_id` set.
  2. A new fact is inserted with the corrected statement.
  3. A "temporal reflection summary" is generated by Sonnet and stored
     as a memory_event so the change is traceable in the episodic feed.

Public API:
  await arbiter.supersede(old_id, new_statement, reason, brand_id)
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime

from ..db import get_db
from .consolidation.synthesizer import generate_reflection
from .stores import semantic as sem_store

logger = logging.getLogger(__name__)


async def supersede(
    old_fact_id: str,
    new_statement: str,
    brand_id: str,
    reason: str = "",
    kind: str | None = None,
    tier: str = "standard",
    importance: float | None = None,
    source_kind: str | None = None,
    source_id: str | None = None,
) -> str:
    """Supersede an existing fact with a new, corrected statement.

    Steps:
      1. Expire the old fact (set expires_at = now).
      2. Generate a Sonnet reflection summary.
      3. Insert the new fact, linking supersedes_id → old_fact_id.
      4. Log a memory_event with the reflection.

    Returns the new fact's id.
    """
    db = get_db()

    # ── 1. Fetch old fact ───────────────────────────────────────────────────
    resp = (
        db.table("memory_semantic")
        .select("statement,kind,tier,importance,brand_id")
        .eq("id", old_fact_id)
        .maybe_single()
        .execute()
    )
    old_row = resp.data or {}
    old_statement = old_row.get("statement", "")
    resolved_kind = kind or old_row.get("kind", "brand_fact")
    resolved_brand = brand_id or old_row.get("brand_id", "")
    resolved_importance = importance if importance is not None else old_row.get("importance", 0.5)

    # ── 2. Expire old fact ──────────────────────────────────────────────────
    now = datetime.now(UTC).isoformat()
    db.table("memory_semantic").update({"expires_at": now}).eq("id", old_fact_id).execute()
    logger.info("arbiter: expired old fact id=%s", old_fact_id)

    # ── 3. Generate reflection summary (non-blocking on error) ──────────────
    reflection = ""
    try:
        reflection = await generate_reflection(
            brand_id=resolved_brand,
            old_statement=old_statement,
            new_statement=new_statement,
            reason=reason,
        )
    except Exception as e:
        logger.warning("arbiter: reflection generation failed: %s", e)

    # ── 4. Insert new fact ──────────────────────────────────────────────────
    new_id = await sem_store.insert_fact(
        brand_id=resolved_brand,
        kind=resolved_kind,  # type: ignore[arg-type]
        statement=new_statement,
        tier=tier,  # type: ignore[arg-type]
        importance=float(resolved_importance),
        source_kind=source_kind,
        source_id=source_id,
        supersedes_id=old_fact_id,
    )
    logger.info("arbiter: new fact id=%s supersedes=%s", new_id, old_fact_id)

    # ── 5. Log memory_event ─────────────────────────────────────────────────
    try:
        db.table("memory_events").insert(
            {
                "brand_id": resolved_brand,
                "event_kind": "memory_supersede",
                "subject_kind": "memory_semantic",
                "subject_id": new_id,
                "summary": reflection or f"Fact superseded: {new_statement[:80]}",
                "payload": {
                    "old_fact_id": old_fact_id,
                    "new_fact_id": new_id,
                    "old_statement": old_statement[:200],
                    "new_statement": new_statement[:200],
                    "reason": reason,
                    "reflection": reflection,
                },
            }
        ).execute()
    except Exception as e:
        logger.warning("arbiter: event log failed: %s", e)

    return new_id


async def resolve_conflicts(
    brand_id: str,
    kind: str | None = None,
    dry_run: bool = False,
) -> list[dict]:
    """Identify groups of very similar (cosine ≥ 0.95) live facts that may
    be conflicting.  Returns candidate pairs for human review.

    This is a best-effort helper — it does NOT auto-supersede.  The Memory
    Inspector UI can surface these pairs and let the user decide.
    """
    facts = await sem_store.list_facts(brand_id=brand_id, kind=kind, limit=500)  # type: ignore[arg-type]
    if len(facts) < 2:
        return []

    # Build embedding list for pairwise comparison
    # Note: we don't re-embed here — we'd need to fetch embeddings from DB.
    # For the MVP this is a stub; P3 will wire in full conflict detection.
    logger.info(
        "arbiter.resolve_conflicts: %d facts loaded for brand=%s (stub — returns empty)",
        len(facts), brand_id,
    )
    return []
