-- Migration 035 — add A/B subject variants to newsletters
--
-- Phase 3: Multi-pass generator produces 2 subject line alternatives.
-- subject_variant_a is always set; subject_variant_b may be null for single-pass fallback.

ALTER TABLE public.newsletters
  ADD COLUMN IF NOT EXISTS subject_variant_a text,
  ADD COLUMN IF NOT EXISTS subject_variant_b text;

COMMENT ON COLUMN public.newsletters.subject_variant_a IS
  'First subject line variant generated by LLM (used as subject if no A/B)';
COMMENT ON COLUMN public.newsletters.subject_variant_b IS
  'Second subject line variant for A/B testing';
